<?php
use \Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\InvokeCommand;
use Drupal\Core\Ajax\HtmlCommand;
use Drupal\Core\Url;
use Drupal\Core\Ajax;
use Drupal\Core\Ajax\OpenModalDialogCommand;
use Drupal\Core\Ajax\ReplaceCommand;

function vendor_content_type_node_presave(Drupal\Core\Entity\EntityInterface $node) {
	if ( $node->type->target_id == "vendor" ) {
	}
}

/**
 * Implements hook_page_preprocess_html().
 */
function vendor_content_type_preprocess_html(&$variables) {
    //Add JS and CSS library
    $variables['#attached']['library'][] = 'vendor_content_type/vendor_content_type';
}


function vendor_content_type_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
	if ( $form_id === 'node_vendor_form' || $form_id == 'node_vendor_edit_form' ) {
		/*-----------------廠商基本資訊---------------------*/
		$node = $form_state->getFormObject()->getEntity();
		$form['vendor_info'] = array(
						'#type' => 'details',
						'#title' => t('廠商基本資訊'),
						'#weight' => -1,
						'#open' => true,
        );

        $form['title']['#group'] = 'vendor_info';
        $form['field_vendor_name']['#group'] = 'vendor_info';
        $form['field_uniform_number']['#group'] = 'vendor_info';
        $form['field_phone']['#group'] = 'vendor_info';
        $form['field_address']['#group'] = 'vendor_info';
        $form['field_fax']['#group'] = 'vendor_info';
        $form['field_email']['#group'] = 'vendor_info';
        $form['field_contact_person']['#group'] = 'vendor_info';
        $form['field_mobile']['#group'] = 'vendor_info';
        
		if ( $node->isNew() ) {
			$vendor_number = "VD-" . date("Ymd");
			while (true) {
                $query = \Drupal::entityQuery("node")
                    					->condition('type', 'vendor')
										->condition('title', $vendor_number, "CONTAINS")
                    					->execute();
				if ( sizeof($query) == 0 ) {
					$vendor_number = "$vendor_number-1";
				} else {
					$vendor_number =  $vendor_number . "-" . (count($query)+ 1);
				}

				$check = \Drupal::entityQuery("node")
                    					->condition('type', 'vendor')
                                        ->condition('title', $vendor_number)
                    					->execute();

				if ( sizeof($check) == 0 ) {
					break;
				}			
			}
			$form ['title']['widget'][0]['value']['#default_value'] = $vendor_number;
		}
        //$form ['title']['#disabled'] = true;

		/*-----------------付款資訊---------------------*/
		$form['payment_info'] = array(
						'#type' => 'details',
						'#title' => t('付款資訊'),
						'#weight' => 9,
							'#open' => true,
        );

		$form['field_bank_name']['#group']= 'payment_info';
		$form['field_branch_name']['#group'] = 'payment_info';
        $form['field_country']['#group'] = 'payment_info';
        $form['field_bank_routing_number']['#group'] = 'payment_info';
        $form['field_account_name']['#group'] = 'payment_info';
        $form['field_payment']['#group'] = 'payment_info';
        $form['field_payment_condition']['#group'] = 'payment_info';
        $form['field_payment_due']['#group'] = 'payment_info';
        $form['field_bank_account']['#group'] = 'payment_info';
	}
}
