<?php
use \Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\InvokeCommand;
use Drupal\Core\Ajax\HtmlCommand;
use Drupal\Core\Ajax;

function product_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
    if ( $form_id == "node_product_form" || $form_id == "node_product_edit_form" ) {
        $form['title']['widget'][0]['value']['#ajax'] = array(
                'callback' => 'ajax_check_unique_id',
				'event' => 'change',
        );

        $form['title_message'] = array(
			'#type' => 'markup',
			'#markup' => '<div class="title-message"></div>',
            '#weight' => 2,
        );
    }
}

function ajax_check_unique_id(array $form, FormStateInterface $form_state) {
	$ajax_response = new AjaxResponse();
	$title = $form_state->getValue('title')[0]['value'];
    
    $ajax_response->addCommand(new HtmlCommand('.title-message', ''));
    $query = \Drupal::entityQuery("node")->condition('type', 'product')->condition('title', $title)->execute();
    if ( count($query) > 0 ) {
        $ajax_response->addCommand(new HtmlCommand('.title-message', '<font color="red">產品編號重複, 請重新命名</font>'));
        $ajax_response->addCommand(new InvokeCommand('#edit-title-0-value', 'val', [""]));
    }
    
	return $ajax_response;
}

