<?php
use \Drupal\Core\Form\FormStateInterface;

/**
 * @ignore
 */
function store_credit_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
    if ( $form_id === 'taxonomy_term_prepaid_balance_form' ) {
        /*$term = $form_state->getFormObject()->getEntity();
        if ( !empty($term->field_to_bill_write_off->target_id) ) {
            $form['actions']['submit']['#disabled'] = true;
        }*/
        $form['actions']['submit']['#disabled'] = true;
    }
}

/**
 * generate store credit unique id.
 *
 * @return string - unique id
 */
function gen_store_credit_id() {
    $total = \Drupal::entityQuery("taxonomy_term")
                    ->condition("vid", "prepaid_balance")
                    ->execute();
    if ( $store_credit_id == null ) {
        return "Credit-" . date("md") . "-" . (count($total) + 1);
    }
}


