<?php
use \Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\InvokeCommand;
use Drupal\Core\Ajax\CssCommand;

function billing_write_off_node_presave(Drupal\Core\Entity\EntityInterface $node) {
    if ( $node->type->target_id == "billing_write_off" ) {
        $query = \Drupal::entityQuery("node");
        $query->condition('type', 'billing');
        $query->condition('field_expected_receive_payment', [$node->field_begin_date->value, $node->field_end_date->value], "BETWEEN");
        $query->condition("field_customer_entity", $node->field_customer_entity->target_id);
        $bill_nids = $query->execute();
        foreach($bill_nids as $bill_nid) {
            $bill = \Drupal\node\Entity\Node::load($bill_nid);
            $bill->set('field_actual_received_payment', date("Y-m-d"));
            $bill->save();
        }
    }
}

function billing_write_off_node_insert(Drupal\Core\Entity\EntityInterface $node) {
    if ( $node->type->target_id == "billing_write_off" ) {
        if ( $node->field_accumulated_advance->value > 0 ) {
            $store_credit = \Drupal\taxonomy\Entity\Term::create(['vid' => 'prepaid_balance']);
            $store_credit->set('name', gen_store_credit_id());
            $store_credit->field_customer_entity->target_id = $node->field_customer_entity->target_id; 
            $store_credit->set('field_create_date', date("Y-m-d"));
            $store_credit->field_from_bill_write_off_entity->target_id = $node->id();
            $store_credit->set('field_store_credit', $node->field_accumulated_advance->value);
            $store_credit->set('status', false);
            $store_credit->save();
        }
        if ( !empty($node->field_store_credit_entity->target_id) ) {
            $store_credit = \Drupal\taxonomy\Entity\Term::load($node->field_store_credit_entity->target_id);
            $store_credit->field_to_bill_write_off->target_id = $node->id();
            $store_credit->save();
        }
    }
}

/*function billing_write_off_node_update(Drupal\Core\Entity\EntityInterface $node) {
    if ( $node->type->target_id == "billing_write_off" ) {
        if ( $node->field_accumulated_advance->value > 0 ) {
            $nids = \Drupal::entityQuery("taxonomy_term")
                    ->condition("vid", "prepaid_balance")
                    ->condition("field_customer_entity", $node->field_customer_entity->target_id)
                    ->condition("field_from_bill_write_off_entity", $node->nid->value)
                    ->execute();
            foreach($nids as $nid) {
                $store_credit = \Drupal\taxonomy\Entity\Term::load($nid);
                if ( round($store_credit->field_store_credit->value) != round($node->field_accumulated_advance->value) ) {
                    $store_credit->set('field_create_date', date("Y-m-d"));
                    $store_credit->set('field_store_credit', $node->field_accumulated_advance->value);
                    $store_credit->save();
                }
            }
        }
    }
}*/

function billing_write_off_node_delete(Drupal\Core\Entity\EntityInterface $node) {
    if ( $node->type->target_id == "billing_write_off" ) {
        $field_sale_purchase_entities = $node->field_sale_purchase_entity;
        for ($i=0; $i < count($field_sale_purchase_entities); $i++) {
            $sale_nid = $field_sale_purchase_entities[$i]->target_id;
            $sale = \Drupal\node\Entity\Node::load($sale_nid);
            $bill_nid = $sale->field_bill->target_id;
            $bill = \Drupal::entityTypeManager()->getStorage("node")->load($bill_nid);
            $bill->delete();
        }
        $nids = \Drupal::entityQuery("taxonomy_term")
                    ->condition("vid", "prepaid_balance")
                    ->condition("field_customer_entity", $node->field_customer_entity->target_id)
                    ->condition("field_from_bill_write_off_entity", $node->nid->value)
                    ->execute();
        foreach($nids as $nid) {
            $entity = \Drupal::entityTypeManager()->getStorage("taxonomy_term")->load($nid);
            $entity->delete();
        }

        //$current = \Drupal::entityTypeManager()->getStorage("node")->load($node->id());
        //$current->delete();
    }
}

function billing_write_off_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
    if ( $form_id === 'node_billing_write_off_form' || $form_id == 'node_billing_write_off_edit_form' ) {
        $node = $form_state->getFormObject()->getEntity();
        $begin_date = $node->field_begin_date->value;
        $end_date = $node->field_end_date->value;
        $customer_nid = $node->field_customer_entity->target_id;
        $customer = \Drupal\node\Entity\Node::load($customer_nid);

        if ( !$node->isNew() ) {
            $form['actions']['submit']['#disabled'] = true;
            //$form['actions']["delete"]['#disabled'] = true;
            $form['actions']["delete"]['#attributes']['style'] = 'display: none;';
        }
        if ( $node->isNew() ) {
            $form ['title']['widget'][0]['value']['#default_value'] = generate_billing_write_off_id($customer_nid);
            $form ['title']['#disabled'] = true;
            $form ['field_actual_received_payment']['widget'][0]['value']['#default_value'] = new \Drupal\Core\Datetime\DrupalDateTime();
            $form ['field_customer_entity']['widget'][0]['target_id']['#default_value'] = $customer;
            $form ['field_customer_entity']['#disabled'] = true;
        }
        $form['field_receivable_balance']['#disabled'] = true;
        $form['field_advance_balance']['#disabled'] = true;
        //$form['field_offset_amount']['#disabled'] = true;
        //$form['field_total_discount']['#disabled'] = true;

        $form['field_cash_amount']['widget'][0]['value']['#prefix'] = '<div id="sign">+</div>';
        $form['field_cash_amount']['widget'][0]['value']['#ajax'] = array('callback' => 'ajax_calculate_prepaid_callback','event' => 'change',);

        $form['field_check_amount']['widget'][0]['value']['#prefix'] = '<div id="sign">+</div>';
        $form['field_check_amount']['widget'][0]['value']['#ajax'] = array('callback' => 'ajax_calculate_prepaid_callback','event' => 'change',);
        $form['field_remittance_amount']['widget'][0]['value']['#prefix'] = '<div id="sign">+</div>';
        $form['field_remittance_amount']['widget'][0]['value']['#ajax'] = array('callback' => 'ajax_calculate_prepaid_callback','event' => 'change',);
        $form['field_remittance_fee']['widget'][0]['value']['#prefix'] = '<div id="sign">+</div>';
        $form['field_remittance_fee']['widget'][0]['value']['#ajax'] = array('callback' => 'ajax_calculate_prepaid_callback','event' => 'change',);
        $form['field_hedgen_amount']['widget'][0]['value']['#prefix'] = '<div id="sign">+</div>';
        $form['field_hedgen_amount']['widget'][0]['value']['#ajax'] = array('callback' => 'ajax_calculate_prepaid_callback','event' => 'change',);
        $form['field_total_discount']['widget'][0]['value']['#prefix'] = '<div id="sign">+</div>';
        $form['field_total_discount']['widget'][0]['value']['#ajax'] = array('callback' => 'ajax_calculate_prepaid_callback','event' => 'change',);
        $form['field_accumulated_advance']['widget'][0]['value']['#prefix'] = '<div id="sign">-</div>';

        $form['field_offset_amount']['widget'][0]['value']['#prefix'] = '<div id="sign">=</div>';

        $form['customer_title'] = array(
            '#title' => '名稱',
            '#type' => 'textfield',
            '#size' => 50,
			'#weight' => 4,
			'#disabled' => true,
            '#default_value' => $customer->field_customer_title->value,
        );


        $form['auto_hedgen'] = array(
			'#type' => 'submit',
			'#value' => t('自動沖帳'),
			'#weight' => 15,
			'#attributes' => [
				'class' => [
					'use-ajax',
				],
			],
			'#ajax' => [
				'callback' => 'ajax_auto_hedgen_callback',
				'event' => 'click',
			],
			'#prefix' => '<div class="auto-hedgen-buttom">',
			'#suffix' => '</div>',
        );

        $form['undo_hedgen'] = array(
			'#type' => 'submit',
			'#value' => t('清除沖帳'),
			'#weight' => 16,
			'#attributes' => [
				'class' => [
					'use-ajax',
				],
			],
			'#ajax' => [
				'callback' => 'ajax_undo_hedgen_callback',
				'event' => 'click',
			],
			'#prefix' => '<div class="undo-hedgen-buttom">',
			'#suffix' => '</div>',
        );

        $form['sell_list_in_table'] = array(
            '#type' => 'table',
            '#weight' => 17,
            '#header' => array('索引', '帳款日期', '單據', '銷售憑證', '銷售總計', '未收金額', '發票編號', '折讓金額', '沖帳金額'),
        );

        $field_receivable_balance = 0;
        $field_advance_balance = 0;
        $field_deposit = 0;
        $sale_entities = [];
        if ( $node->isNew() ) {
            $index = 1;
            $query = \Drupal::entityQuery("node");
            $query->condition('type', 'billing');
            $query->condition('field_expected_receive_payment', [$begin_date, $end_date], "BETWEEN");
            $query->condition("field_customer_entity", $customer_nid);
            $bill_nids = $query->execute();
            foreach($bill_nids as $bill_nid) {
                $bill = \Drupal\node\Entity\Node::load($bill_nid);
                $sale = \Drupal\node\Entity\Node::load($bill->field_order_id->target_id);
                if ( $sale->moderation_state->value != "done" && $sale->moderation_state->value != "return_completed" ) {
                    $field_deposit = $field_deposit + $bill->field_deposit->value;
                    $sale_entities[] = array('target_id' => $bill->field_order_id->target_id);
                    $field_receivable_balance = $field_receivable_balance + $bill->field_remain_unpaid_amount->value;
                    $form['sell_list_in_table'][$index]['index'] = array(
                        '#type' => 'textfield',
                        '#title' => t('索引'),
                        '#title_display' => 'invisible',
                        '#size' => 15,
                        '#disabled' => true,
                        '#default_value' => $index,
                    );
                    $form['sell_list_in_table'][$index]['field_expected_receive_payment'] = array(
                        '#type' => 'textfield',
                        '#title' => t('帳款日期'),
                        '#title_display' => 'invisible',
                        '#disabled' => true,
                        '#default_value' => $bill->field_expected_receive_payment->value,
                    );
                    $form['sell_list_in_table'][$index]['field_bill_type'] = array(
                        '#type' => 'textfield',
                        '#title' => t('單據'),
                        '#size' => 20,
                        '#title_display' => 'invisible',
                        '#disabled' => true,
                        '#default_value' => get_entity_storage_label($bill, 'field_bill_type', $bill->field_bill_type->value),
                    );
                    $form['sell_list_in_table'][$index]['field_order_id'] = array(
                        '#title' => t('銷售憑證'),
                        '#title_display' => 'invisible',
                        '#size' => 90,
                        '#prefix' => '<a href="/node/' . $bill->field_order_id->target_id .'/edit" target="_blank">' . getSellOrderID($bill->field_order_id->target_id) . '</a>',
                    );
                    $form['sell_list_in_table'][$index]['field_total_amount_with_tax'] = array(
                        '#type' => 'textfield',
                        '#title' => t('銷售總計'),
                        '#title_display' => 'invisible',
                        '#disabled' => true,
                        '#default_value' => $bill->field_total_amount_with_tax->value,
                    );
                    $form['sell_list_in_table'][$index]['field_remain_unpaid_amount'] = array(
                        '#type' => 'textfield',
                        '#title' => t('未收金額'),
                        '#title_display' => 'invisible',
                        '#disabled' => true,
                        '#default_value' => $bill->field_remain_unpaid_amount->value,
                    );
                    $form['sell_list_in_table'][$index]['field_receipt_number'] = array(
                        '#type' => 'textfield',
                        '#title' => t('發票編號'),
                        '#title_display' => 'invisible',
                        '#default_value' => $bill->field_receipt_number->value,
                    );
                    $form['sell_list_in_table'][$index]['field_discount'] = array(
                        '#type' => 'textfield',
                        '#title' => t('折讓金額'),
                        '#title_display' => 'invisible',
                        '#default_value' => $bill->field_discount->value,
                        '#ajax' => [
                            'callback' => 'ajax_calculate_total_discount_callback',
                            'event' => 'change',
                        ],
                    );
                    $form['sell_list_in_table'][$index]['field_offset_amount'] = array(
                        '#type' => 'textfield',
                        '#title' => t('沖帳金額'),
                        '#title_display' => 'invisible',
                        '#default_value' => $bill->field_write_off_amount->value,
                    );
                    $index++;
                }
            };
            $form['field_cash_amount']['widget'][0]['value']['#default_value'] = $field_deposit;
            $node->field_sale_purchase_entity = $sale_entities;
            $form ['field_receivable_balance']['widget'][0]['value']['#default_value'] = $field_receivable_balance;
            $store_credit_tids = \Drupal::entityQuery("taxonomy_term")
                                        ->condition("vid", "prepaid_balance")
                                        ->condition("field_customer_entity", $customer_nid)
                                        ->condition("field_to_bill_write_off", NULL, 'IS NULL')
                                        ->execute();
            foreach($store_credit_tids as $store_credit_tid) {
                $store_credit = \Drupal\taxonomy\Entity\Term::load($store_credit_tid);
                $field_advance_balance = $field_advance_balance + round($store_credit->field_store_credit->value);
                $form ['field_advance_balance']['widget'][0]['value']['#default_value'] = $field_advance_balance;
                $node->field_store_credit_entity = array('target_id' => $store_credit_tid);
                break;
            }
            $paid = round($field_advance_balance+$field_deposit);
            if ( paid == 0 ) {
                $form ['field_offset_amount']['widget'][0]['value']['#default_value'] = 0;
            } else {
                $prepaid = round($paid - $field_receivable_balance);
                if ( $prepaid > 0 ) {
                    $form['field_accumulated_advance']['widget'][0]['value']['#default_value'] = $prepaid;
                    $form ['field_offset_amount']['widget'][0]['value']['#default_value'] = $field_receivable_balance;    
                } else if ( $prepaid < 0 ) {
                    $prepaid = $prepaid * -1;
                    $form ['field_offset_amount']['widget'][0]['value']['#default_value'] = $prepaid;
                } else {
                    $form ['field_offset_amount']['widget'][0]['value']['#default_value'] = 0;
                }    
            }
        } else {
            $sale_entities = $node->field_sale_purchase_entity;
            $index = 1;
            foreach($sale_entities as $sale_entity) {
                $sale = \Drupal\node\Entity\Node::load($sale_entity->target_id);
                $bill = \Drupal\node\Entity\Node::load($sale->field_bill->target_id);
                $form['sell_list_in_table'][$index]['index'] = array(
                        '#type' => 'textfield',
                        '#title' => t('索引'),
                        '#title_display' => 'invisible',
                        '#size' => 15,
                        '#disabled' => true,
                        '#default_value' => $index,
                    );
                $form['sell_list_in_table'][$index]['field_expected_receive_payment'] = array(
                    '#type' => 'textfield',
                    '#title' => t('帳款日期'),
                    '#title_display' => 'invisible',
                    '#disabled' => true,
                    '#default_value' => $bill->field_expected_receive_payment->value,
                );
                $form['sell_list_in_table'][$index]['field_bill_type'] = array(
                    '#type' => 'textfield',
                    '#title' => t('單據'),
                    '#size' => 20,
                    '#title_display' => 'invisible',
                    '#disabled' => true,
                    '#default_value' => get_entity_storage_label($bill, 'field_bill_type', $bill->field_bill_type->value),
                );
                $form['sell_list_in_table'][$index]['field_order_id'] = array(
                    '#title' => t('銷售憑證'),
                    '#title_display' => 'invisible',
                    '#size' => 90,
                    '#prefix' => '<a href="/node/' . $bill->field_order_id->target_id .'/edit" target="_blank">' . getSellOrderID($bill->field_order_id->target_id) . '</a>',
                );
                $form['sell_list_in_table'][$index]['field_total_amount_with_tax'] = array(
                    '#type' => 'textfield',
                    '#title' => t('銷售總計'),
                    '#title_display' => 'invisible',
                    '#disabled' => true,
                    '#default_value' => $bill->field_total_amount_with_tax->value,
                );
                $form['sell_list_in_table'][$index]['field_remain_unpaid_amount'] = array(
                    '#type' => 'textfield',
                    '#title' => t('未收金額'),
                    '#title_display' => 'invisible',
                    '#disabled' => true,
                    '#default_value' => $bill->field_remain_unpaid_amount->value,
                );
                $form['sell_list_in_table'][$index]['field_receipt_number'] = array(
                    '#type' => 'textfield',
                    '#title' => t('發票編號'),
                    '#title_display' => 'invisible',
                    '#default_value' => $bill->field_receipt_number->value,
                );
                $form['sell_list_in_table'][$index]['field_discount'] = array(
                    '#type' => 'textfield',
                    '#title' => t('折讓金額'),
                    '#title_display' => 'invisible',
                    '#default_value' => $bill->field_discount->value,
                    '#ajax' => [
                        'callback' => 'ajax_calculate_total_discount_callback',
                        'event' => 'change',
                    ],
                );
                $form['sell_list_in_table'][$index]['field_offset_amount'] = array(
                    '#type' => 'textfield',
                    '#title' => t('沖帳金額'),
                    '#title_display' => 'invisible',
                    '#default_value' => $bill->field_write_off_amount->value,
                );
                $index++;
            }
        }

        $form['comment_section'] = [
			'#group' => 'advanced',
			'#type' => 'details',
			'#title' => t('備註'),
			'#attributes' => [
				'class' => ['node-form-options']
			],
			'#attached' => [
				'library' => ['node/drupal.node'],
			],
			'#optional' => true,
			'#open' => true,
		];

		$form['field_long_comment']['#group'] = 'comment_section';

        array_unshift($form['actions']['submit']['#submit'], '_mySubmit');
        $form['#attached']['library'][] = 'billing_write_off/billing_write_off';
    }
}

function _mySubmit(array &$form, FormStateInterface $form_state) {
    $node = $form_state->getFormObject()->getEntity();
    $begin_date = $node->field_begin_date->value;
    $end_date = $node->field_end_date->value;
    $customer_nid = $node->field_customer_entity->target_id;
    $query = \Drupal::entityQuery("node");
    $query->condition('type', 'billing');
    $query->condition('field_expected_receive_payment', [$begin_date, $end_date], "BETWEEN");
    $query->condition("field_customer_entity", $customer_nid);
    $bill_nids = $query->execute();
    $index=1;
    foreach($bill_nids as $bill_nid) {
        $bill = \Drupal\node\Entity\Node::load($bill_nid);
        $field_receipt_number = $form_state->getValue('sell_list_in_table')[$index]['field_receipt_number'];
        $field_discount = $form_state->getValue('sell_list_in_table')[$index]['field_discount'];
        $field_offset_amount = $form_state->getValue('sell_list_in_table')[$index]['field_offset_amount'];
        $bill->set('field_receipt_number', $field_receipt_number);
        $bill->set('field_discount', $field_discount);
        $bill->set('field_write_off_amount', $field_offset_amount);
        $bill->save();
        $index++;
    }
}

function ajax_calculate_prepaid_callback(array $form, FormStateInterface $form_state) {
    $ajax_response = new AjaxResponse();
    $field_receivable_balance = $form_state->getValue('field_receivable_balance')[0]['value'];
    if ( $field_receivable_balance > 0 ) {
        $field_advance_balance = $form_state->getValue('field_advance_balance')[0]['value'];
        $field_cash_amount = $form_state->getValue('field_cash_amount')[0]['value'];
        $field_check_amount = $form_state->getValue('field_check_amount')[0]['value'];
        $field_remittance_amount = $form_state->getValue('field_remittance_amount')[0]['value'];
        $field_remittance_fee = $form_state->getValue('field_remittance_fee')[0]['value'];
        $field_hedgen_amount = $form_state->getValue('field_hedgen_amount')[0]['value'];
        $field_total_discount = $form_state->getValue('field_total_discount')[0]['value'];

        $paid = round($field_advance_balance+$field_cash_amount+$field_check_amount+$field_remittance_amount+$field_remittance_fee+$field_hedgen_amount+$field_total_discount);
        $prepaid = round($paid - $field_receivable_balance);
        $remaining = 0;
        if ( $prepaid > 0 ) {
            $ajax_response->addCommand(new InvokeCommand('#edit-field-accumulated-advance-0-value', 'val', [$prepaid]));
            $remaining = $paid - $prepaid;
        } else {
            $ajax_response->addCommand(new InvokeCommand('#edit-field-accumulated-advance-0-value', 'val', [0]));
            $remaining = $paid;
        }
        
        $ajax_response->addCommand(new InvokeCommand('#edit-field-offset-amount-0-value', 'val', [$remaining]));
    }
    
	return $ajax_response;
}

function ajax_auto_hedgen_callback(array $form, FormStateInterface $form_state){
    $ajax_response = new AjaxResponse();
    $node = $form_state->getFormObject()->getEntity();
    $begin_date = $node->field_begin_date->value;
    $end_date = $node->field_end_date->value;
    $customer_nid = $node->field_customer_entity->target_id;
    $query = \Drupal::entityQuery("node");
    $query->condition('type', 'billing');
    $query->condition('field_expected_receive_payment', [$begin_date, $end_date], "BETWEEN");
    $query->condition("field_customer_entity", $customer_nid);
    $bill_nids = $query->execute();
    for($i=1; $i <= count($bill_nids); $i++) {
        $field_remain_unpaid_amount = $form_state->getValue('sell_list_in_table')[$i]['field_remain_unpaid_amount'];
        $field_discount = $form_state->getValue('sell_list_in_table')[$i]['field_discount'];
        $field_remain_unpaid_amount = $field_remain_unpaid_amount - $field_discount;
        $ajax_response->addCommand(new InvokeCommand('#edit-sell-list-in-table-' . $i . '-field-offset-amount', 'val', [$field_remain_unpaid_amount]));
    }
    
    return $ajax_response;
}

function ajax_undo_hedgen_callback(array $form, FormStateInterface $form_state){
    $ajax_response = new AjaxResponse();
    $node = $form_state->getFormObject()->getEntity();
    $begin_date = $node->field_begin_date->value;
    $end_date = $node->field_end_date->value;
    $customer_nid = $node->field_customer_entity->target_id;
    $query = \Drupal::entityQuery("node");
    $query->condition('type', 'billing');
    $query->condition('field_expected_receive_payment', [$begin_date, $end_date], "BETWEEN");
    $query->condition("field_customer_entity", $customer_nid);
    $bill_nids = $query->execute();
    for($i=1; $i <= count($bill_nids); $i++) {
        $ajax_response->addCommand(new InvokeCommand('#edit-sell-list-in-table-' . $i . '-field-offset-amount', 'val', [""]));
    }
    
    return $ajax_response;
}

function ajax_calculate_total_discount_callback(array $form, FormStateInterface $form_state) {
    $ajax_response = new AjaxResponse();
    $node = $form_state->getFormObject()->getEntity();
    $begin_date = $node->field_begin_date->value;
    $end_date = $node->field_end_date->value;
    $customer_nid = $node->field_customer_entity->target_id;
    $query = \Drupal::entityQuery("node");
    $query->condition('type', 'billing');
    $query->condition('field_expected_receive_payment', [$begin_date, $end_date], "BETWEEN");
    $query->condition("field_customer_entity", $customer_nid);
    $bill_nids = $query->execute();
    $total_discount = 0;
    for($i=1; $i <= count($bill_nids); $i++) {
        $field_discount = $form_state->getValue('sell_list_in_table')[$i]['field_discount'];
        $total_discount = $total_discount + $field_discount;
    }

    $ajax_response->addCommand(new InvokeCommand('#edit-field-total-discount-0-value', 'val', [$total_discount]));

    $field_receivable_balance = $form_state->getValue('field_receivable_balance')[0]['value'];
    $field_advance_balance = $form_state->getValue('field_advance_balance')[0]['value'];
    $field_cash_amount = $form_state->getValue('field_cash_amount')[0]['value'];
    $field_check_amount = $form_state->getValue('field_check_amount')[0]['value'];
    $field_remittance_amount = $form_state->getValue('field_remittance_amount')[0]['value'];
    $field_remittance_fee = $form_state->getValue('field_remittance_fee')[0]['value'];
    $field_hedgen_amount = $form_state->getValue('field_hedgen_amount')[0]['value'];

    $paid = round($field_advance_balance+$field_cash_amount+$field_check_amount+$field_remittance_amount+$field_remittance_fee+$field_hedgen_amount+$total_discount);
    $prepaid = round($paid - $field_receivable_balance);
    $remaining = 0;
    if ( $prepaid > 0 ) {
        $ajax_response->addCommand(new InvokeCommand('#edit-field-accumulated-advance-0-value', 'val', [$prepaid]));
        $remaining = $paid - $prepaid;
    } else {
        $ajax_response->addCommand(new InvokeCommand('#edit-field-accumulated-advance-0-value', 'val', [0]));
        $remaining = $paid;
    }
    $ajax_response->addCommand(new InvokeCommand('#edit-field-offset-amount-0-value', 'val', [$remaining]));
    
    return $ajax_response;
}

function generate_billing_write_off_id($customer_nid) {
	$billing_write_off_id = "W-$customer_nid-" . date("Ym");
	while (true) {
		$query = \Drupal::entityQuery("node")
								->condition('type', 'billing_write_off')
								->condition('title', $billing_write_off_id, "CONTAINS")
								->execute();
		if ( sizeof($query) == 0 ) {
			$billing_write_off_id = "$billing_write_off_id-1";
		} else {
			$billing_write_off_id =  $billing_write_off_id . "-" . (count($query)+ 1);
		}

		$check = \Drupal::entityQuery("node")
								->condition('type', 'billing_write_off')
								->condition('title', $billing_write_off_id)
								->execute();

		if ( sizeof($check) == 0 ) {
			break;
		}
	}
	return $billing_write_off_id;
}

